apiVersion: v1
kind: ConfigMap
metadata:
  name: product-config
  namespace: ecommerce
data:
  POSTGRES_HOST: postgres.data.svc.cluster.local
  POSTGRES_PORT: "5432"

  REDIS_HOST: redis.data.svc.cluster.local
  REDIS_PORT: "6379"

  DJANGO_SETTINGS_MODULE: config.settings.dev