# Generated by Django 5.0.14 on 2026-03-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=377183, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_name',
            field=models.CharField(default=3534, max_length=255),
            preserve_default=False,
        ),
    ]
